AWSTemplateFormatVersion: '2010-09-09'

Description: Taller de AWS con CloudFormation - Migración de Información para Análisis en un Restaurante

Parameters:
  companyName:
    Type: String
    Description: name of the glorious company
    Default: thechaoscompany

Resources:
  TraceabilityDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join [ '-', [traceability-table, !Ref companyName] ]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: date
        Enabled: true
  BackupS3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join [ '-', [data-migration-bucket, !Ref companyName] ]